-- Generated from SQLite for Supabase Postgres
BEGIN;

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price TEXT NOT NULL,
  description TEXT,
  icon TEXT,
  color TEXT,
  tag TEXT
);

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE,
  name TEXT,
  username TEXT UNIQUE,
  phone TEXT UNIQUE,
  address TEXT,
  gender TEXT,
  password_hash TEXT NOT NULL,
  role TEXT DEFAULT 'user',
  profile_complete INTEGER DEFAULT 0,
  seen_profile_prompt INTEGER DEFAULT 0,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

TRUNCATE TABLE public.products RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.users RESTART IDENTITY CASCADE;

INSERT INTO public.products (id, name, price, description, icon, color, tag) VALUES
(1, 'Laptop Dell Inspiron 15', '15.500.000đ', 'Core i5 Gen 12, RAM 8GB, SSD 512GB', '💻', 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)', 'Bán chạy'),
(2, 'Laptop Asus Vivobook', '13.200.000đ', 'Core i3 Gen 11, RAM 8GB, SSD 256GB', '💻', 'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)', 'Giá tốt'),
(3, 'PC Gaming RTX 3060', '22.000.000đ', 'Core i5, RTX 3060, RAM 16GB, SSD 512GB', '🖥️', 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)', 'Hot'),
(4, 'Laptop Lenovo ThinkPad', '18.700.000đ', 'Core i7 Gen 12, RAM 16GB, SSD 512GB', '💻', 'linear-gradient(135deg, #f6d365 0%, #fda085 100%)', 'Doanh nhân'),
(5, 'PC Văn Phòng Mini', '8.500.000đ', 'Core i3, RAM 8GB, SSD 256GB, nhỏ gọn', '🖥️', 'linear-gradient(135deg, #84fab0 0%, #8fd3f4 100%)', 'Tiết kiệm'),
(6, 'MacBook Air M2', '26.900.000đ', 'Chip M2, RAM 8GB, SSD 256GB, siêu mỏng nhẹ', '💻', 'linear-gradient(135deg, #d9afd9 0%, #97d9e1 100%)', 'Cao cấp'),
(7, 'PC Gaming RTX 4070', '35.000.000đ', 'Core i7, RTX 4070, RAM 32GB, SSD 1TB', '🖥️', 'linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%)', 'Cấu hình khủng'),
(8, 'Laptop Acer Aspire', '11.900.000đ', 'Core i3 Gen 11, RAM 8GB, SSD 256GB', '💻', 'linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)', 'Sinh viên'),
(9, 'Laptop Dell Inspiron 15', '15.500.000đ', 'Core i5 Gen 12, RAM 8GB, SSD 512GB', '💻', 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)', 'Bán chạy'),
(10, 'Laptop Asus Vivobook', '13.200.000đ', 'Core i3 Gen 11, RAM 8GB, SSD 256GB', '💻', 'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)', 'Giá tốt'),
(11, 'PC Gaming RTX 3060', '22.000.000đ', 'Core i5, RTX 3060, RAM 16GB, SSD 512GB', '🖥️', 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)', 'Hot'),
(12, 'Laptop Lenovo ThinkPad', '18.700.000đ', 'Core i7 Gen 12, RAM 16GB, SSD 512GB', '💻', 'linear-gradient(135deg, #f6d365 0%, #fda085 100%)', 'Doanh nhân'),
(13, 'PC Văn Phòng Mini', '8.500.000đ', 'Core i3, RAM 8GB, SSD 256GB, nhỏ gọn', '🖥️', 'linear-gradient(135deg, #84fab0 0%, #8fd3f4 100%)', 'Tiết kiệm'),
(14, 'MacBook Air M2', '26.900.000đ', 'Chip M2, RAM 8GB, SSD 256GB, siêu mỏng nhẹ', '💻', 'linear-gradient(135deg, #d9afd9 0%, #97d9e1 100%)', 'Cao cấp'),
(15, 'PC Gaming RTX 4070', '35.000.000đ', 'Core i7, RTX 4070, RAM 32GB, SSD 1TB', '🖥️', 'linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%)', 'Cấu hình khủng'),
(16, 'Laptop Acer Aspire', '11.900.000đ', 'Core i3 Gen 11, RAM 8GB, SSD 256GB', '💻', 'linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)', 'Sinh viên');

INSERT INTO public.users (id, email, name, username, phone, address, gender, password_hash, role, profile_complete, seen_profile_prompt, created_at) VALUES
(1, 'test@example.com', 'Test User', NULL, NULL, NULL, NULL, '$2a$10$r/n.SVllKeXobXCJE2IFFOgDNLllFnfnvs4EbbzNozmPDQx1wUKki', 'user', 0, 0, '2026-08-21 13:56:09'),
(2, 'longuser2@no-email.local', NULL, 'longuser2', '0909000111', NULL, NULL, '$2a$10$61edP65qiyyEhUXyaxrvrePq3HMmFu3SfEWCLMuE6pKYtBPaayGfW', 'user', 0, 0, '2026-08-21 14:04:10'),
(3, 'Long@gmail.com', 'Lương Văn Long', 'Long', '0937112113', 'P. Long Bình - Đồng Nai', 'male', '$2a$10$lIThS3wn6hgcFlC7U.FeEeaSbVo/Rpf.tmQmRJN3QI0WtbtnALg0C', 'user', 1, 0, '2026-08-21 14:11:34'),
(4, 'Hai@no-email.local', 'LVH', 'Hai', '0912005522', 'DN', 'male', '$2a$10$8nZRh3cO6FgJrHy4UoIXve3ugbDbpMur9j2lCekSsJvVOB2.Rs9AG', 'user', 0, 1, '2026-08-21 14:59:14'),
(5, 'Nam@no-email.local', 'NVN', 'Nam', '123456789', 'ĐN', 'male', '$2a$10$Y5AGT5CST7Dn/.whun5t/OPnzFfEGynpsRNKADLFwzVTwwKTpNhq2', 'user', 0, 1, '2026-08-21 15:50:30'),
(6, 'Bắc@no-email.local', 'NVB', 'Bắc', '0123456789', 'ĐN', 'male', '$2a$10$ZAYZtfw5W4ANzkcJE3CFcOTFgX9yyHwfqUzorQQipmhmR7c4/sEEm', 'user', 0, 0, '2026-08-21 15:53:43'),
(7, 'Tây@no-email.local', 'NVT', 'Tây', '012012012', 'ĐN', 'male', '$2a$10$.cJYaxPjsOdGXb4xRsmW1.kaJv4cZNdrVlqmgGA7HPnmHNYcx2oMC', 'user', 0, 1, '2026-08-21 15:55:13');

SELECT setval(pg_get_serial_sequence('public.products', 'id'), COALESCE((SELECT MAX(id) FROM public.products), 1), true);
SELECT setval(pg_get_serial_sequence('public.users', 'id'), COALESCE((SELECT MAX(id) FROM public.users), 1), true);

COMMIT;
